# -*- coding: utf-8 -*-
"""week 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ehOsiRX9mJg_lFR6jJJScFZD1_TFL0X
"""

# Task 1
print("Hello, World!")

# Brief Introduction
print("My name is Afifa Mehak Luqman.")
print("I am currently doing an internship to improve my programming skills.")

# Task 2
def calculate_power(base, exponent):
    return base ** exponent

def calculate_modulo(a, b):
    return a % b

base = 2
exponent = 5
a = 17
b = 3

print(f"{base} to the power of {exponent} is {calculate_power(base, exponent)}")
print(f"{a} modulo {b} is {calculate_modulo(a, b)}")

# Task 3
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))

largest = max(num1, num2, num3)
smallest = min(num1, num2, num3)

print(f"The largest number is: {largest}")
print(f"The smallest number is: {smallest}")

# Task 4
import math

def area_trapezoid(base1, base2, height):
    return 0.5 * (base1 + base2) * height

def area_ellipse(a, b):
    return math.pi * a * b

base1 = 5
base2 = 7
height = 4

a = 3
b = 2

print(f"Area of trapezoid: {area_trapezoid(base1, base2, height)}")
print(f"Area of ellipse: {area_ellipse(a, b)}")

# Task 5
total_seconds = int(input("Enter time in seconds: "))

hours = total_seconds // 3600
remaining_seconds = total_seconds % 3600
minutes = remaining_seconds // 60
seconds = remaining_seconds % 60

print(f"{total_seconds} seconds = {hours} hours, {minutes} minutes, and {seconds} seconds")