# -*- coding: utf-8 -*-
"""week3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PX8P3GMTGycnpiTkfvO3AuPwO24VOEMY
"""

def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr)
        L = arr[:mid]
        R = arr[mid:]
        merge_sort(L)
        merge_sort(R)
        i = j = k = 0
        while i < len(L) and j < len(R):
            if L[i] < R[j]:
                arr[k] = L[i]
                i += 1
            else:
                arr[k] = R[j]
                j += 1
            k += 1
        while i < len(L):
            arr[k] = L[i]
            i += 1
            k += 1
        while j < len(R):
            arr[k] = R[j]
            j += 1
            k += 1
nums = [38, 27, 43, 3, 9, 82, 10]
print("Original List:", nums)
merge_sort(nums)
print("Sorted List:", nums)

def reverse_list(lst):
    reversed_list = []
    for i in range(len(lst)-1, -1, -1):
        reversed_list.append(lst[i])
    return reversed_list

original = [10, 20, 30, 40, 50]
reversed_list = reverse_list(original)

print("Original List:", original)
print("Reversed List:", reversed_list)

import string

def longest_word(sentence):
    for char in string.punctuation:
        sentence = sentence.replace(char, "")

    words = sentence.split()
    longest = max(words, key=len)
    return longest

sentence = input("Enter a sentence: ")
print("Longest word is:", longest_word(sentence))

def is_palindrome(s):
    cleaned = ''.join(s.split()).lower()
    return cleaned == cleaned[::-1]

text = input("Enter a string: ")
if is_palindrome(text):
    print("It's a palindrome.")
else:
    print("Not a palindrome.")

from collections import Counter
import string
def most_frequent_word(file_path):
    try:
        with open(file_path, 'r') as file:
            text = file.read().lower()
            # Remove punctuation
            for char in string.punctuation:
                text = text.replace(char, "")
            words = text.split()
            word_counts = Counter(words)
            most_common = word_counts.most_common(1)[0]
            return most_common
    except FileNotFoundError:
        return None
file_path = "/content/week3.txt"
result = most_frequent_word(file_path)
if result:
    word, count = result
    print(f"The most frequent word is '{word}' and it appears {count} times.")
else:
    print("File not found. Please check the file name or upload it.")

from google.colab import files

uploaded = files.upload()